"""Calibrated action coordinates for the game surfaces."""

from dataclasses import dataclass
from typing import Dict, Iterable

@dataclass(frozen=True)
class Action:
    x: int
    y: int
    desc: str


ACTIONS: Dict[str, Action] = {
    "patrol_truck": Action(82, 738, "home patrol truck"),
    "patrol_claim": Action(347, 696, "patrol income claim"),
    "quick_patrol": Action(143, 697, "quick patrol/ad patrol button"),
    "quick_patrol_icon": Action(120, 696, "quick patrol left icon/video area"),
    "patrol_close": Action(422, 237, "close patrol panel"),
    "reward_dismiss": Action(250, 820, "dismiss reward popup"),
    "ad_close_top": Action(468, 75, "top-right ad close"),
    "ad_close_lower": Action(468, 578, "lower floating ad/card close"),
    "calendar_top": Action(318, 119, "top calendar entry on home"),
    "calendar_gift": Action(340, 270, "calendar visible gift"),
    "calendar_close": Action(423, 202, "calendar weekly/activity page close button"),
    "right_menu": Action(428, 162, "home right-side hamburger expandable menu"),
    "mail_entry": Action(390, 211, "mail entry after opening the top-right menu"),
    "mail_claim_all": Action(252, 720, "mail one-click claim button"),
    "mail_reward_popup_dismiss": Action(250, 315, "dismiss mail reward popup or safely tap mail header"),
    "mail_close": Action(425, 226, "mail page close button"),
    "mail_menu_dismiss": Action(250, 450, "safe home-center tap to dismiss the top-right menu"),
    "welfare_cluster": Action(428, 392, "right-side welfare/gift cluster"),
    "welfare_reward_popup_dismiss": Action(250, 600, "dismiss the seven-day welfare free-reward popup"),
    "pass_entry": Action(430, 332, "right-side battle pass entry on home"),
    "pass_free_claim": Action(112, 837, "battle pass free one-click claim"),
    "work_plan_tab": Action(354, 902, "battle pass work-plan tab"),
    "work_plan_sign": Action(387, 844, "work-plan free sign-in button"),
    "battle_tab": Action(250, 900, "bottom battle tab"),
    "legion_tab": Action(367, 900, "bottom legion tab"),
    "journey_tab": Action(404, 900, "bottom journey tab"),
    "base_tab": Action(312, 900, "bottom base tab"),
    "base_back": Action(38, 79, "return from base to home"),
    "training_hall": Action(164, 425, "base training hall entry"),
    "cafeteria": Action(355, 393, "base cafeteria entry"),
    "cafeteria_claim": Action(254, 912, "cafeteria one-click claim"),
    "cafeteria_back": Action(89, 910, "return from cafeteria to base"),
    "training_reward_dismiss": Action(250, 575, "dismiss training-hall reward popup"),
    "global_rescue_challenge": Action(358, 613, "global rescue challenge"),
    "global_rescue_free": Action(82, 277, "global rescue free reward"),
    "terminal_crisis_challenge": Action(323, 339, "terminal crisis challenge"),
    "terminal_crisis_sweep": Action(165, 840, "terminal crisis free sweep"),
    "terminal_crisis_confirm": Action(320, 579, "confirm terminal crisis sweep"),
    "training_hall_scroll_area": Action(252, 500, "training hall scrollable list center"),
    "training_hall_drag_start": Action(252, 700, "training hall list lower drag point"),
    "training_hall_drag_end": Action(252, 220, "training hall list upper drag point"),
    "training_hall_back": Action(85, 908, "return from training hall to base"),
    "battle_challenge": Action(322, 505, "battlefield contest challenge"),
    "battle_modal_challenge": Action(355, 845, "battlefield contest lower challenge"),
    "battle_castle": Action(128, 805, "battlefield contest lower-left castle"),
    "battle_modal_drag_start": Action(250, 580, "battlefield contest list lower drag point"),
    "battle_modal_drag_end": Action(250, 330, "battlefield contest list upper drag point"),
    "battle_sweep_last": Action(375, 578, "last battlefield contest sweep"),
    "battle_modal_close": Action(425, 228, "close battlefield contest modal"),
    "battle_page_back": Action(84, 875, "return from battlefield contest to training hall"),
    "element_challenge": Action(322, 835, "element trial challenge"),
    "core_trial": Action(255, 380, "core trial entry"),
    "idle_button": Action(76, 225, "core trial idle button"),
    "idle_claim": Action(254, 635, "claim idle reward popup"),
    "idle_cancel": Action(420, 270, "close idle reward popup"),
    "core_sweep": Action(254, 565, "core trial sweep"),
    "core_sweep_ten": Action(184, 551, "core trial ten-time sweep"),
    "core_sweep_close": Action(420, 270, "close core trial sweep dialog"),
    "core_trial_back": Action(85, 908, "return from core trial"),
    "element_back": Action(85, 908, "return from element trial"),
    "play_shop": Action(407, 145, "training hall play shop entry"),
    "play_shop_enhancer": Action(358, 513, "play shop enhancer purchase button"),
    "play_shop_battle_tab": Action(215, 798, "play shop battlefield contest tab"),
    "play_shop_battle_drag_start": Action(252, 733, "play shop battlefield list lower drag point inside modal"),
    "play_shop_battle_drag_end": Action(252, 283, "play shop battlefield list upper drag point"),
    "play_shop_gun_blueprint": Action(358, 641, "play shop gun blueprint purchase button"),
    "play_shop_tabs_drag_start": Action(345, 798, "play shop tab strip drag start (right)"),
    "play_shop_tabs_drag_end": Action(145, 798, "play shop tab strip drag end (left)"),
    "play_shop_element_tab": Action(280, 798, "play shop element trial tab after left drag"),
    "play_shop_base_material": Action(358, 644, "play shop base material purchase button"),
    "play_shop_legion_tab": Action(390, 798, "play shop legion play tab"),
    "play_shop_skill_manual": Action(358, 500, "play shop random skill manual purchase button"),
    "play_shop_max": Action(345, 566, "play shop maximum quantity button"),
    "play_shop_buy": Action(252, 616, "play shop purchase confirmation button"),
    "play_shop_reward_dismiss": Action(250, 633, "dismiss play shop reward popup"),
    "play_shop_modal_close": Action(401, 350, "close play shop purchase modal"),
    "play_shop_close": Action(426, 214, "close play shop"),
    "journey_gold_claim": Action(368, 444, "visible journey gold resource bubble"),
    "journey_wood_claim": Action(229, 544, "visible journey wood resource bubble"),
    "legion_daily_cut": Action(282, 548, "legion daily-cut entry"),
    "legion_cut_once": Action(254, 797, "free daily-cut button before it becomes a diamond cost"),
    "legion_foreign_challenge": Action(121, 356, "legion foreign challenge entry"),
    "legion_sweep": Action(200, 909, "foreign challenge free sweep button"),
    "legion_sweep_cancel": Action(187, 579, "foreign challenge sweep cancellation"),
    "legion_sweep_confirm": Action(321, 579, "foreign challenge free sweep confirmation"),
    "legion_reward_left": Action(82, 116, "left reward tab inside foreign challenge"),
    "legion_reward_claim_top": Action(356, 302, "top visible legion reward claim button"),
    "legion_reward_claim_row1": Action(356, 270, "visible legion reward claim row 1"),
    "legion_reward_claim_row2": Action(356, 359, "visible legion reward claim row 2"),
    "legion_reward_claim_row3": Action(356, 448, "visible legion reward claim row 3"),
    "legion_reward_claim_row4": Action(356, 537, "visible legion reward claim row 4"),
    "legion_reward_claim_row5": Action(356, 626, "visible legion reward claim row 5"),
    "legion_reward_claim_row6": Action(356, 715, "visible legion reward claim row 6"),
    "legion_personal_reward_tab": Action(218, 793, "personal reward tab inside foreign challenge rewards"),
    "legion_personal_reward_claim_top": Action(356, 302, "first visible personal legion reward claim"),
    "legion_reward_panel_close": Action(427, 214, "close legion reward panel"),
    "legion_foreign_challenge_back": Action(86, 909, "return from foreign challenge to legion"),
    "legion_reward_popup_dismiss": Action(250, 600, "dismiss legion reward popup"),
    "legion_modal_close": Action(425, 228, "close legion inner modal"),
    "legion_shop": Action(355, 421, "legion shop entry on legion hub"),
    "legion_shop_drag_start": Action(252, 760, "legion shop list lower drag point"),
    "legion_shop_drag_end": Action(252, 120, "legion shop list upper drag point"),
    "legion_shop_gun_blueprint": Action(356, 436, "legion shop gun blueprint purchase button"),
    "legion_shop_base_powder": Action(356, 581, "legion shop base powder purchase button"),
    "legion_shop_enhancer": Action(356, 726, "legion shop enhancer purchase button"),
    "legion_shop_max": Action(345, 566, "legion shop maximum quantity button"),
    "legion_shop_buy": Action(252, 614, "legion shop purchase confirmation button"),
    "legion_shop_reward_dismiss": Action(250, 600, "dismiss legion shop reward popup"),
    "legion_shop_modal_close": Action(401, 350, "close legion shop purchase modal"),
    "legion_shop_close": Action(426, 214, "close legion shop"),
    "shop_tab": Action(84, 885, "bottom-left shop tab"),
    "shop_resource_tab": Action(105, 849, "shop resource tab"),
    "shop_resource_drag_start": Action(252, 760, "shop resource page lower drag point"),
    "shop_resource_drag_end": Action(252, 120, "shop resource page upper drag point"),
    "shop_resource_gold600_free": Action(255, 605, "shop resource gold x600 direct free"),
    "shop_special_pack_tab": Action(405, 849, "shop special-pack tab"),
    "shop_gold_free": Action(253, 413, "shop special-pack direct free gold"),
    "back_top_left": Action(38, 79, "top-left back button"),
    "back_bottom_left": Action(84, 914, "bottom-left page back button"),
    "close_top_right": Action(468, 75, "top-right close button"),
}




def action_names() -> Iterable[str]:
    return sorted(ACTIONS)
